name: COVID
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.0+4
  cupertino_icons: ^0.1.2
  charts_flutter: ^0.9.0
  recase: ^3.0.0
  shared_preferences: ^0.5.7+2
  curved_navigation_bar: ^0.3.2
  
  
dev_dependencies:
  flutter_test:
    sdk: flutter


      

flutter:

  uses-material-design: true

  assets:
      - assets/images/cough.gif
      - assets/images/3622110.jpg
      - assets/images/therm.gif
      - assets/images/intro.jpg
      - assets/images/startloading.gif
      - assets/images/lung.gif
      - assets/images/sorethroat.gif
      - assets/images/masks.gif
      - assets/images/sanitise.gif
      - assets/images/socialdistancing.gif
      - assets/images/quarantine.gif
      - assets/images/load.gif
      
   

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/montserrat/Montserrat-Regular.ttf

    - family: Jost
      fonts:
        - asset: assets/fonts/Jost/Jost-VariableFont_wght.ttf
      
    - family: Cookie
      fonts:
        - asset: assets/fonts/Cookie-Regular.ttf

